[tool.black]
line-length = 88
target-version = ["py39"]

[tool.isort]
profile = "black"
known_first_party = "project"
known_django = "django"
sections = ["FUTURE", "STDLIB", "DJANGO", "FIRSTPARTY", "THIRDPARTY", "LOCALFOLDER"]
